name: AppApoderado
options:
  createIntermediateGroups: true

targets:
  AppApoderado:
    type: application
    platform: iOS
    deploymentTarget: "13.0"
    # XcodeGen parses resources (including .xcassets and .storyboard) from `sources`.
    # Keeping the asset catalog under `sources` ensures it gets compiled into Assets.car.
    sources:
      - path: Sources
      - path: Resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.gladiatorcontrolbase.guardian
        INFOPLIST_FILE: Resources/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        MARKETING_VERSION: 1.0
        CURRENT_PROJECT_VERSION: 4
        CODE_SIGN_STYLE: Automatic
        SWIFT_VERSION: 5.0

schemes:
  AppApoderado:
    build:
      targets:
        AppApoderado: all
